-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: make sort
        language: system
        types: [python]

    -   id: flake8
        name: Flake8
        # I get the following error if jobs is more than 1:
        # AttributeError: 'pep257Checker' object has no attribute 'convention'
        # Try to remove the `--jobs=1` in the future when someone might
        # have fixed the underlying problem.
        entry: pipenv run flake8 --jobs=1
        language: system
        types: [python]

    -   id: black
        name: black
        entry: pipenv run black
        language: system
        types: [python]

    -   id: trailing-whitespace
        name: Trim Trailing Space
        entry: pipenv run trailing-whitespace-fixer
        language: system
        types: [non-executable, file, text]
        exclude_types: [svg]

    -   id: end-of-file-fixer
        name: Fix End of Files
        description: Ensures that a file is either empty, or ends with one newline.
        entry: pipenv run end-of-file-fixer
        language: system
        types: [non-executable, file, text]
        exclude_types: [svg]

    -   id: check-merge-conflict
        name: Check for merge conflicts
        description: Check for files that contain merge conflict strings.
        entry: pipenv run check-merge-conflict
        language: system
        stages: [push]

    -   id: codespell
        name: Check Spelling
        description: Checks for common misspellings in text files.
        entry: pipenv run codespell --ignore-words .aspell.en.pws
        language: system
        types: [non-executable, file, text]
        exclude_types: [svg]
        stages: [push]

    -   id: debug-statements
        name: Check Debug Statements Absent (Python)
        description: Checks that debug statements (pdb, ipdb, pudb) are not imported on commit.
        entry: pipenv run debug-statement-hook
        language: system
        types: [python]
        stages: [push]
